package main

import (
	"html"
	"strconv"
	"strings"
	"time"

	checker "github.com/pawel-cygal/certops/internal/check"
	"github.com/pawel-cygal/certops/internal/verify"
)

func writeReportsHTML(path, title string, reports []checker.Report) error {
	var b strings.Builder
	writeHTMLStart(&b, title)
	ok, warn, critical := reportCounts(reports)
	b.WriteString("<main class=\"shell\">\n")
	b.WriteString("<section class=\"hero\"><p class=\"eyebrow\">SysTeam Ops Tools</p><h1>" + html.EscapeString(title) + "</h1><p class=\"sub\">TLS and HTTPS posture report for CI/CD, client evidence, and operational review.</p></section>\n")
	b.WriteString("<section class=\"meta-grid\">")
	writeCard(&b, "targets", formatInt(len(reports)))
	writeCard(&b, "ok", formatInt(ok))
	writeCard(&b, "warn", formatInt(warn))
	writeCard(&b, "critical", formatInt(critical))
	writeCard(&b, "generated at", generatedAt())
	writeCard(&b, "run id", runID())
	b.WriteString("</section>\n")
	b.WriteString("<section class=\"panel\"><div class=\"panel-head\"><h2>Endpoints</h2><span class=\"badge ")
	if critical > 0 {
		b.WriteString("critical\">critical")
	} else if warn > 0 {
		b.WriteString("warn\">warn")
	} else {
		b.WriteString("ok\">ok")
	}
	b.WriteString("</span></div><table><thead><tr><th>target</th><th>status</th><th>expires in</th><th>expires at</th><th>issuer</th><th>tls</th><th>hsts</th><th>findings</th></tr></thead><tbody>\n")
	for _, report := range reports {
		b.WriteString("<tr>")
		writeTD(&b, report.Target)
		writeTDClass(&b, report.Status, report.Status)
		writeTD(&b, formatDays(report.Certificate.DaysRemaining))
		writeTD(&b, prettyTimestamp(report.Certificate.NotAfter))
		writeTD(&b, shortIssuer(report.Certificate.Issuer))
		writeTD(&b, strings.Join(report.TLS.SupportedVersions, ", "))
		writeTD(&b, yesNo(strings.TrimSpace(report.HTTPS.HSTS) != ""))
		writeTD(&b, firstFinding(report.Findings))
		b.WriteString("</tr>\n")
	}
	b.WriteString("</tbody></table>\n")
	b.WriteString("</section>\n")
	writeHTMLFindings(&b, reports)
	b.WriteString("<p class=\"footer\">Generated by certops. JSON/YAML/PROM output remains available for automation.</p>\n")
	b.WriteString("</main>\n")
	writeHTMLEnd(&b)
	return writeFileAtomic(path, []byte(b.String()), 0644)
}

func writeVerifyHTML(path string, report verify.Report) error {
	var b strings.Builder
	writeHTMLStart(&b, "certops verify")
	b.WriteString("<main class=\"shell\">\n")
	b.WriteString("<section class=\"hero\"><p class=\"eyebrow\">SysTeam Ops Tools</p><h1>certops verify</h1><p class=\"sub\">TLS expected-state verification report for CI/CD and operational evidence.</p></section>\n")
	b.WriteString("<section class=\"meta-grid\">")
	writeCard(&b, "file", report.File)
	writeCard(&b, "targets", formatInt(report.Total))
	writeCard(&b, "matched", formatInt(report.Matched))
	writeCard(&b, "failed", formatInt(report.Errors))
	writeCard(&b, "generated at", generatedAt())
	writeCard(&b, "run id", runID())
	b.WriteString("</section>\n")
	b.WriteString("<section class=\"panel\"><div class=\"panel-head\"><h2>Checks</h2><span class=\"badge ")
	if report.Errors > 0 {
		b.WriteString("critical\">failed")
	} else {
		b.WriteString("ok\">ok")
	}
	b.WriteString("</span></div><table><thead><tr><th>name</th><th>target</th><th>status</th><th>expires in</th><th>tls</th><th>detail</th></tr></thead><tbody>\n")
	for _, result := range report.Results {
		detail := "-"
		if len(result.Findings) > 0 {
			detail = result.Findings[0].Message
		} else if result.Error != "" {
			detail = result.Error
		}
		b.WriteString("<tr>")
		writeTD(&b, result.Name)
		writeTD(&b, result.Target)
		writeTDClass(&b, result.Status, result.Status)
		writeTD(&b, formatDays(result.Report.Certificate.DaysRemaining))
		writeTD(&b, strings.Join(result.Report.TLS.SupportedVersions, ", "))
		writeTD(&b, detail)
		b.WriteString("</tr>\n")
	}
	b.WriteString("</tbody></table>\n")
	b.WriteString("</section>\n")
	b.WriteString("<p class=\"footer\">Generated by certops. JSON/YAML/PROM output remains available for automation.</p>\n")
	b.WriteString("</main>\n")
	writeHTMLEnd(&b)
	return writeFileAtomic(path, []byte(b.String()), 0644)
}

func writePlanHTML(path string, report planReport) error {
	return writePlanLikeHTML(path, "certops plan", report.File, report.Status, report.Summary, report.Items, "PKI desired-state plan for CA, inventory, trust, and service readiness.")
}

func writeDriftHTML(path string, report driftReport) error {
	return writePlanLikeHTML(path, "certops drift", report.File, report.Status, report.Summary, report.Items, "PKI drift report for CI/CD evidence and operational review.")
}

func writeFleetTrustHTML(path string, report fleetTrustReport) error {
	var b strings.Builder
	title := "certops fleet trust " + report.Action
	writeHTMLStart(&b, title)
	b.WriteString("<main class=\"shell\">\n")
	b.WriteString("<section class=\"hero\"><p class=\"eyebrow\">SysTeam Ops Tools</p><h1>" + html.EscapeString(title) + "</h1><p class=\"sub\">Remote trust-store operation report for PKI readiness and host drift evidence.</p></section>\n")
	b.WriteString("<section class=\"meta-grid\">")
	writeCard(&b, "file", report.File)
	writeCard(&b, "status", report.Status)
	writeCard(&b, "total", formatInt(report.Summary.Total))
	writeCard(&b, "ok", formatInt(report.Summary.OK))
	writeCard(&b, "warn", formatInt(report.Summary.Warn))
	writeCard(&b, "critical", formatInt(report.Summary.Critical))
	writeCard(&b, "generated at", generatedAt())
	writeCard(&b, "run id", runID())
	b.WriteString("</section>\n")
	b.WriteString("<section class=\"panel\"><div class=\"panel-head\"><h2>Targets</h2><span class=\"badge ")
	if report.Summary.Critical > 0 {
		b.WriteString("critical\">critical")
	} else if report.Summary.Warn > 0 {
		b.WriteString("warn\">warn")
	} else {
		b.WriteString("ok\">ok")
	}
	b.WriteString("</span></div><table><thead><tr><th>host</th><th>endpoint</th><th>ca</th><th>status</th><th>path</th><th>message</th></tr></thead><tbody>\n")
	for _, item := range report.Items {
		b.WriteString("<tr>")
		writeTD(&b, item.Host)
		writeTD(&b, hostEndpoint(item.Address, item.Port))
		writeTD(&b, item.CA)
		writeTDClass(&b, item.Status, item.Status)
		writeTD(&b, item.Path)
		writeTD(&b, item.Message)
		b.WriteString("</tr>\n")
	}
	if len(report.Items) == 0 {
		b.WriteString("<tr><td colspan=\"6\">no fleet trust targets</td></tr>\n")
	}
	b.WriteString("</tbody></table></section>\n")
	if len(report.Errors) > 0 {
		b.WriteString("<section class=\"panel findings\"><div class=\"panel-head\"><h2>Errors</h2></div><table><thead><tr><th>host</th><th>ca</th><th>error</th></tr></thead><tbody>\n")
		for _, errItem := range report.Errors {
			b.WriteString("<tr>")
			writeTD(&b, errItem.Host)
			writeTD(&b, errItem.CA)
			writeTD(&b, errItem.Error)
			b.WriteString("</tr>\n")
		}
		b.WriteString("</tbody></table></section>\n")
	}
	b.WriteString("<p class=\"footer\">Generated by certops. JSON/YAML output remains available for automation.</p>\n")
	b.WriteString("</main>\n")
	writeHTMLEnd(&b)
	return writeFileAtomic(path, []byte(b.String()), 0644)
}

func writePlanLikeHTML(path, title, file, status string, summary planSummary, items []planItem, subtitle string) error {
	var b strings.Builder
	writeHTMLStart(&b, title)
	b.WriteString("<main class=\"shell\">\n")
	b.WriteString("<section class=\"hero\"><p class=\"eyebrow\">SysTeam Ops Tools</p><h1>" + html.EscapeString(title) + "</h1><p class=\"sub\">" + html.EscapeString(subtitle) + "</p></section>\n")
	b.WriteString("<section class=\"meta-grid\">")
	writeCard(&b, "file", file)
	writeCard(&b, "status", status)
	writeCard(&b, "total", formatInt(summary.Total))
	writeCard(&b, "manual", formatInt(summary.Manual))
	writeCard(&b, "warn", formatInt(summary.Warn))
	writeCard(&b, "critical", formatInt(summary.Critical))
	writeCard(&b, "generated at", generatedAt())
	writeCard(&b, "run id", runID())
	b.WriteString("</section>\n")
	b.WriteString("<section class=\"panel\"><div class=\"panel-head\"><h2>Items</h2><span class=\"badge ")
	if summary.Critical > 0 {
		b.WriteString("critical\">critical")
	} else if summary.Warn > 0 {
		b.WriteString("warn\">warn")
	} else {
		b.WriteString("ok\">ok")
	}
	b.WriteString("</span></div><table><thead><tr><th>action</th><th>scope</th><th>target</th><th>status</th><th>change</th><th>expected</th><th>actual</th></tr></thead><tbody>\n")
	for _, item := range items {
		b.WriteString("<tr>")
		writeTD(&b, item.Action)
		writeTD(&b, item.Scope)
		writeTD(&b, item.Target)
		writeTDClass(&b, item.Status, item.Status)
		writeTD(&b, item.Change)
		writeTD(&b, item.Expected)
		writeTD(&b, item.Actual)
		b.WriteString("</tr>\n")
	}
	if len(items) == 0 {
		b.WriteString("<tr><td colspan=\"7\">no drift detected</td></tr>\n")
	}
	b.WriteString("</tbody></table></section>\n")
	b.WriteString("<p class=\"footer\">Generated by certops. JSON/YAML output remains available for automation.</p>\n")
	b.WriteString("</main>\n")
	writeHTMLEnd(&b)
	return writeFileAtomic(path, []byte(b.String()), 0644)
}

func writeHTMLStart(b *strings.Builder, title string) {
	b.WriteString("<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>")
	b.WriteString(html.EscapeString(title))
	b.WriteString("</title><style>")
	b.WriteString(":root{color-scheme:dark;--bg:#080d19;--panel:#101827;--panel2:#121d31;--line:#25324a;--text:#e8edf7;--muted:#91a0b8;--cyan:#7ddfff;--ok:#5ee787;--warn:#f7c948;--critical:#ff6b6b}")
	b.WriteString("*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at top left,#13213a 0,#080d19 42%,#050812 100%);color:var(--text);font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif}")
	b.WriteString(".shell{max-width:1180px;margin:0 auto;padding:40px 24px 56px}.hero{margin-bottom:24px}.eyebrow{margin:0 0 8px;color:var(--cyan);font:700 12px/1.2 ui-monospace,SFMono-Regular,Menlo,monospace;text-transform:uppercase;letter-spacing:.16em}.hero h1{margin:0;font-size:36px;letter-spacing:-.02em}.sub{max-width:760px;color:var(--muted);font-size:16px}")
	b.WriteString(".meta-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin:24px 0}@media(max-width:760px){.meta-grid{grid-template-columns:1fr 1fr}}.card{background:rgba(16,24,39,.82);border:1px solid var(--line);border-radius:10px;padding:14px 16px}.card .label{color:var(--muted);font-size:12px;text-transform:uppercase;letter-spacing:.08em}.card .value{margin-top:6px;font-weight:650;word-break:break-word}")
	b.WriteString(".panel{background:rgba(16,24,39,.9);border:1px solid var(--line);border-radius:12px;overflow:hidden;box-shadow:0 24px 80px rgba(0,0,0,.32);margin-top:18px}.panel-head{display:flex;align-items:center;justify-content:space-between;padding:16px 18px;border-bottom:1px solid var(--line);background:rgba(18,29,49,.75)}.panel h2{margin:0;font-size:18px}.badge{border:1px solid currentColor;border-radius:999px;padding:4px 10px;font-size:12px;font-weight:700;text-transform:uppercase}.ok{color:var(--ok)}.warn{color:var(--warn)}.critical,.error{color:var(--critical)}")
	b.WriteString("table{border-collapse:collapse;width:100%}th,td{text-align:left;padding:11px 14px;border-bottom:1px solid var(--line);font-size:14px;vertical-align:top}th{color:var(--cyan);font-weight:700;background:#0d1525}tr:last-child td{border-bottom:0}.findings{margin-top:28px}.footer{margin:18px 0 0;color:var(--muted);font-size:13px}")
	b.WriteString("</style></head><body>\n")
}

func writeHTMLEnd(b *strings.Builder) {
	b.WriteString("</body></html>\n")
}

func writeHTMLFindings(b *strings.Builder, reports []checker.Report) {
	hasFindings := false
	for _, report := range reports {
		if len(report.Findings) > 0 {
			hasFindings = true
			break
		}
	}
	if !hasFindings {
		return
	}
	b.WriteString("<section class=\"panel findings\"><div class=\"panel-head\"><h2>Findings</h2></div><table><thead><tr><th>target</th><th>severity</th><th>scope</th><th>message</th></tr></thead><tbody>\n")
	for _, report := range reports {
		for _, finding := range report.Findings {
			b.WriteString("<tr>")
			writeTD(b, report.Target)
			writeTDClass(b, finding.Severity, finding.Severity)
			writeTD(b, finding.Scope)
			writeTD(b, finding.Message)
			b.WriteString("</tr>\n")
		}
	}
	b.WriteString("</tbody></table></section>\n")
}

func writeTD(b *strings.Builder, value string) {
	b.WriteString("<td>")
	b.WriteString(html.EscapeString(emptyDash(value)))
	b.WriteString("</td>")
}

func writeTDClass(b *strings.Builder, class, value string) {
	b.WriteString("<td class=\"")
	b.WriteString(html.EscapeString(class))
	b.WriteString("\">")
	b.WriteString(html.EscapeString(emptyDash(value)))
	b.WriteString("</td>")
}

func firstFinding(findings []checker.Finding) string {
	if len(findings) == 0 {
		return "-"
	}
	return findings[0].Message
}

func formatDays(days int) string {
	if days == 0 {
		return "0 days"
	}
	return formatInt(days) + " days"
}

func formatSummary(matched, total, errors int) string {
	return formatInt(matched) + "/" + formatInt(total) + " matched, " + formatInt(errors) + " failed"
}

func formatInt(v int) string {
	return strconv.Itoa(v)
}

func writeCard(b *strings.Builder, label, value string) {
	b.WriteString("<div class=\"card\"><div class=\"label\">")
	b.WriteString(html.EscapeString(label))
	b.WriteString("</div><div class=\"value\">")
	b.WriteString(html.EscapeString(emptyDash(value)))
	b.WriteString("</div></div>")
}

func reportCounts(reports []checker.Report) (ok, warn, critical int) {
	for _, report := range reports {
		switch report.Status {
		case "critical", "error":
			critical++
		case "warn":
			warn++
		default:
			ok++
		}
	}
	return ok, warn, critical
}

func generatedAt() string {
	return time.Now().Format("2006-01-02 15:04 MST")
}

func runID() string {
	return time.Now().UTC().Format("20060102T150405Z")
}
